module.exports.descriptors = [
    'Bamboo',
    'Golden',
    'Jungle',
    'Mystic',
    'Sacred',
    'Spice',
    'Silent',
    'Crimson',
    'Lotus',
    'Mango',
    'Royal',
    'Elephant',
    'Cascading',
    'Monsoon',
    'Turmeric',
    'Taj',
    'Saffron',
    'Silk',
    'Jasmine',
    'Amber',
    'Marigold',
    'Divine',
    'Verdant',
    'Coral',
    'Tiger',
    'Teak',
    'Ruby',
    'Majestic',
    'Vibrant',
    'Sanskrit',
    'Mumbai',
    'Ganges',
    'Kerala',
    'Maharaja',
    'Gandhi',
    'Spiritual'
];

module.exports.places = [
    'Harbor',
    'Village',
    'Meadow',
    'Ghat',
    'Bazaar',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ashram',
    'Jungle',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Oasis',
    'Ridge',
    'Gorge',
    'Summit',
    'Lagoon',
    'Treetop',
    'Valley',
    'Glade',
    'Marsh',
    'Citadel',
    'Plateau',
    'Tundra',
    'Sanctuary',
    'Temple',
    'Tea Estate',
    'Fort',
    'Palace'
];
